### ISSUE TITLE
The iOS Simulator cannot enter Chinese /iOS 版本无法输入中文

### ISSUE THREAD

**Issue by AuTtx** [chenxi92/ChatGPT#3]
With the Chinese input method switched, Chinese cannot be input on the iPhone simulator
在切换了中文输入法的情况下，在iPhone模拟器上无法输入中文

**Comment by chenxi92** [comment]
open your iOS Simulator and select `I/O` -> `Keyboard` and check `Toggle Software Keyboard` ( or type `Command` + `K`), and then switch to Chinese at the keyboard.

**Comment by AuTtx** [comment]
Thanks a lot.I have solved the problem by adding a Chinese keyboard to the Settings on the home page of the simulator. Changes in the simulator I/O do not seem to be entered in Chinese (I have tried this method).

> open your iOS Simulator and select `I/O` -> `Keyboard` and check `Toggle Software Keyboard` ( or type `Command` + `K`), and then switch to Chinese at the keyboard.
